import { combineReducers } from 'redux';
import { reducer as formReducer } from 'redux-form';
import {
  games,
  gamesLoadHasFailed,
  gamesIsLoading,
  gamesToggleDialog,
  gamesIsAdding,
  gamesAddHasFailed,
  gamesIsDeleting,
  gamesDeleteHasFailed,
} from './games';
import {
  genres,
  genresLoadHasFailed,
  genresIsLoading,
  genresToggleDialog,
  genresIsAdding,
  genresAddHasFailed,
  genresIsDeleting,
  genresDeleteHasFailed,
} from './genres';
import {
  platforms,
  platformsLoadHasFailed,
  platformsIsLoading,
  platformsToggleDialog,
  platformsIsAdding,
  platformsAddHasFailed,
  platformsIsDeleting,
  platformsDeleteHasFailed,
} from './platforms';

export default combineReducers({
  form: formReducer,
  games,
  gamesLoadHasFailed,
  gamesIsLoading,
  gamesIsDialogOpen: gamesToggleDialog,
  gamesIsAdding,
  gamesAddHasFailed,
  gamesIsDeleting,
  gamesDeleteHasFailed,
  genres,
  genresLoadHasFailed,
  genresIsLoading,
  genresIsDialogOpen: genresToggleDialog,
  genresIsAdding,
  genresAddHasFailed,
  genresIsDeleting,
  genresDeleteHasFailed,
  platforms,
  platformsLoadHasFailed,
  platformsIsLoading,
  platformsIsDialogOpen: platformsToggleDialog,
  platformsIsAdding,
  platformsAddHasFailed,
  platformsIsDeleting,
  platformsDeleteHasFailed,
});
